### ISSUE TITLE
Lista a completar para la entrega

### ISSUE THREAD

**Issue by cnmorales** [mnmaita/dragonskale#97]
- [ ] el orden de los tiles para que el fuego quede por encima siempre
- [x] las flechas, quizas q vayan mas despacio y sean mas grandes
- [x] los controles del draco 
- [x] olas en el mapa 
- [x] spawnear escamas de manera aleatoria al matar enemigos/edificioes
- [x] sprite de las escamas
- [x] curarte al agarrar escamas 
- [x] Arte de main menu
- [x] Pagina en Itch
- [ ] Pantalla tutorial donde explica el objetivo y los controles
- [ ] Bug audio que sigue reproduciendo cuando no hay mas fuego
- [x] Spawnear mas enemigos a medida q pasa mas tiempo
- [ ] Transformar soldados en barcos cuando estan sobre el agua

**Comment by mnmaita** [comment]
Cierro. Abri un issue por cada item que no estaba en el proyecto aun.
